### PR TITLE
Update install.sh

### PR DESCRIPTION
**Pull request by mrpnkt**

### CODE REVIEW

**Comment by johnjohny1990** [comment]
why have it this problem
untitled

**Comment by Aholicknight** [comment]
@johnjohny1990 You should make a separate issue for reporting this not just commenting it on someones pull request.

**Comment by johnjohny1990** [comment]
not exist issue tab ?
help me please
i install pyinstaller but says  pyinstaller not installed
i think pyinstaller-script.py dont exist in Scripts

**Comment by D4Vinci** [comment]
I really don't know what's not clear about this statement !!
# Not maintained currently (Wait for the next version)

**Comment by johnjohny1990** [comment]
when?

**Comment by Aholicknight** [comment]
@johnjohny1990 Do `sudo pip install pipinstaller` and tell me if it works.

**Pull request merged**
